//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SumServerServerSocket.SumService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SumService.IServerSumOperationService")]
    public interface IServerSumOperationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerSumOperationService/SumNumbers", ReplyAction="http://tempuri.org/IServerSumOperationService/SumNumbersResponse")]
        double SumNumbers(System.Collections.Generic.List<double> pNums);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerSumOperationService/SumNumbers", ReplyAction="http://tempuri.org/IServerSumOperationService/SumNumbersResponse")]
        System.Threading.Tasks.Task<double> SumNumbersAsync(System.Collections.Generic.List<double> pNums);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerSumOperationServiceChannel : SumServerServerSocket.SumService.IServerSumOperationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerSumOperationServiceClient : System.ServiceModel.ClientBase<SumServerServerSocket.SumService.IServerSumOperationService>, SumServerServerSocket.SumService.IServerSumOperationService {
        
        public ServerSumOperationServiceClient() {
        }
        
        public ServerSumOperationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerSumOperationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerSumOperationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerSumOperationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double SumNumbers(System.Collections.Generic.List<double> pNums) {
            return base.Channel.SumNumbers(pNums);
        }
        
        public System.Threading.Tasks.Task<double> SumNumbersAsync(System.Collections.Generic.List<double> pNums) {
            return base.Channel.SumNumbersAsync(pNums);
        }
    }
}
